env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  arrow-parens:
    - warn
    - as-needed
  no-unused-expressions: off
  no-sequences: off
  no-return-assign: off
ignorePatterns:
  - "public/javascripts/*.js"
